version: "3.7"

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    networks:
      - backbone
    volumes:
      - "./wg:/config/wg_confs/"
      - "/lib/modules:/lib/modules:ro"
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
  ytdl:
    image: bennythink/ytdlbot
    env_file:
      - env/ytdl.env
    restart: unless-stopped
    depends_on:
      - wireguard
    network_mode: service:wireguard
    volumes:
      - ./data/vnstat/:/var/lib/vnstat/

networks:
  backbone:
    driver: bridge
